function [fitresult, gof] = sinFit1(xData, yData, omega, predPara, fnum)
%CREATEFIT(CX,C)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : cx
%      Y Output: c
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jun-2020 16:53:09


%% Fit: 'untitled fit 1'.
figure(1)
%[xData, yData] = prepareCurveData( cx, c );

% Set up fittype and options.
funcSting = ['a0 + a1 * sin(' num2str(omega) ' * x + c)']; 
ft = fittype( funcSting, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = predPara;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure(fnum)
%figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Y vs. X', 'sin fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel cx
ylabel c
grid on


